version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise:10.2.4
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
  tempo:
    image: grafana/tempo:2.3.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "9095:9095"
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml
    command: [ "--config.file=/etc/mimir.yaml" ]
    ports:
      - "9009:9009"
  collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    ports:
      - "4318:4318"
    command: "--config /etc/otel-config.yaml"
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
  flask:
    image: simple-flask-calc
    build: ./simple-test
    ports:
      - "5000:5000"
      
      
  #hotrod:
    #image: jaegertracing/example-hotrod:latest
    #ports:
      #- "8080:8080"
    #command: ["all"]
    #environment:
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318
      #- OTEL_EXPORTER_OTLP_INSECURE=true
    
