receivers:
 otlp:
   protocols:
     http:
       endpoint: 0.0.0.0:4318

processors:
 batch:

exporters:
 otlphttp/traces:
   endpoint: http://tempo:4318
   tls:
     insecure: true
 otlphttp/logs:
   endpoint: http://loki:3100/otlp
   tls:
     insecure: true
 prometheusremotewrite/metrics:
   endpoint: http://mirmir:9009/api/v1/push

service:
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [otlphttp/traces]
   logs:
     receivers: [otlp]
     processors: [batch]
     exporters: [otlphttp/logs]
   metrics:
     receivers: [otlp]
     processors: [batch]
     exporters: [prometheusremotewrite/metrics]
