receivers:
 otlp:
   protocols:
     http:
       endpoint: 0.0.0.0:4318

processors:
 batch:

exporters:
 otlphttp/traces:
   endpoint: http://tempo:4318
   tls:
     insecure: true
 loki/logs:
   endpoint: http://loki:3100/loki/api/v1/push
 prometheusremotewrite/metrics:
   endpoint: http://mimir:9009/api/v1/push
   tls:
     insecure: true
 debug:
   

service:
 telemetry:
   logs:
     level: "info"
 pipelines:
   traces:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, otlphttp/traces]
   logs:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, loki/logs]
   metrics:
     receivers: [otlp]
     processors: [batch]
     exporters: [debug, prometheusremotewrite/metrics]
